### ISSUE TITLE
[enhancement] IP references in setup and start processes

### ISSUE THREAD

**Issue by Marcos-A** [FherStk/teaching-stats-setup#10]
To solve possible misconfigurations when the app is being installed in a container and ports are being redirected, the setup process should offer an option to add the proper IP for it to be added to the Google Authentication instructions, Django social account instructions, the Metabase password setup instructions, access addresses when starting the app, as well as to the ALLOWED_HOSTS parameter of the settings.py Django file. The script could ask for a redirecting address when a container is used and replace the values that reference the IP.

**Comment by FherStk** [comment]
From now on, only the "teaching-stats.com" domain will be used. This simplifies a lot the installation process, because the IP doesn't matter, but needs a new entry within the local machine's host file (which is always needed when running within a LXD container or similar). 

This approach has been chosen because the only installer that exists right now is the "localhost" one, which is intended for local development. In a near future, a new "production environment" setup will be provided.
