### ISSUE TITLE
[enhancement] Misleading user names and passwords in setup instructions

### ISSUE THREAD

**Issue by Marcos-A** [FherStk/teaching-stats-setup#11]
It should be made clear thatPostgreSQL and Django admin share the same username "teaching-stats", and that both share the same password provided during the setup process. It should be stated that the Django superuser email required during the setup process is just for notification purposes to avoid users thinking of it as a username.

Besides, Metabase admin could be called "teaching-stats" as well for consistency and simplicity.

**Comment by FherStk** [comment]
The same user, email and password will be used along all the installation, and new info is being displayed in order to clarify this:

Some data will be collected at the beginning:
![image](https://user-images.githubusercontent.com/324326/165718599-6379aab3-34d3-4e8f-bf1b-4691d4f95054.png)

Also, reminders are displayed:
![image](https://user-images.githubusercontent.com/324326/165723578-a23a2bcb-7df8-4ac6-ba3b-63dd66bd3195.png)

![image](https://user-images.githubusercontent.com/324326/165723192-65273eaa-3ace-41af-8323-3dfa93872051.png)

![image](https://user-images.githubusercontent.com/324326/165730941-b59c3834-b907-472d-94d6-5ca8285def18.png)
