### ISSUE TITLE
[enhancement] Django social account setup

### ISSUE THREAD

**Issue by Marcos-A** [FherStk/teaching-stats-setup#9]
- Django social account setup instructions should be accessible from outside the installation process.
- Installation process should be able to be interrupted and resumed to set up the Django social account process.

**Comment by FherStk** [comment]
The process can be interrupted, and this step will be resumed when the setup starts again. 
The installer has been improved and no Django setup is manually needed, just the Google Developers Console configuration, because the API keys must be provided. So, once the process is completed and the keys provided, the installer will setup the correct Django configuration, so the process cannot be skipped, just postponed, and is not intended to allow modifications.
